package servidorAlertas.dto;


/**
* servidorAlertas/dto/AlertaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public final class AlertaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public servidorAlertas.dto.IndicadoresDTO indicadores;
  public String fecha = "";
  public String hora = "";
  public int puntuacion = (int)0;

  public AlertaDTO ()
  {
      this.indicadores =  new IndicadoresDTO();
  } // ctor

  public AlertaDTO (servidorAlertas.dto.IndicadoresDTO _indicadores, String _fecha, String _hora, int _puntuacion)
  {
    indicadores = _indicadores;
    fecha = _fecha;
    hora = _hora;
    puntuacion = _puntuacion;
  } // ctor

} // class AlertaDTO
