package servidorAlertas.dto;

/**
* servidorAlertas/dto/AlertaDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public final class AlertaDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorAlertas.dto.AlertaDTO value = null;

  public AlertaDTOHolder ()
  {
  }

  public AlertaDTOHolder (servidorAlertas.dto.AlertaDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorAlertas.dto.AlertaDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorAlertas.dto.AlertaDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorAlertas.dto.AlertaDTOHelper.type ();
  }

}
