package servidorAlertas.dto;

/**
* servidorAlertas/dto/IndicadoresDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public final class IndicadoresDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorAlertas.dto.IndicadoresDTO value = null;

  public IndicadoresDTOHolder ()
  {
  }

  public IndicadoresDTOHolder (servidorAlertas.dto.IndicadoresDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorAlertas.dto.IndicadoresDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorAlertas.dto.IndicadoresDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorAlertas.dto.IndicadoresDTOHelper.type ();
  }

}
