package servidorAlertas.dto;


/**
* servidorAlertas/dto/IndicadoresDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public final class IndicadoresDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int frecuenciaCardiaca = (int)0;
  public int frecuenciaRespiratoria = (int)0;
  public float temperatura = (float)0;
  public int idPaciente = (int)0;

  public IndicadoresDTO ()
  {
  } // ctor

  
  public IndicadoresDTO (int _frecuenciaCardiaca, int _frecuenciaRespiratoria, float _temperatura, int _idPaciente)
  {
    frecuenciaCardiaca = _frecuenciaCardiaca;
    frecuenciaRespiratoria = _frecuenciaRespiratoria;
    temperatura = _temperatura;
    idPaciente = _idPaciente;
  } // ctor

  /*
    public IndicadoresDTO(int i, int i0, int i1, int id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
  */
    public int getFrecuenciaCardiaca() {
        return frecuenciaCardiaca;
    }

    public void setFrecuenciaCardiaca(int frecuenciaCardiaca) {
        this.frecuenciaCardiaca = frecuenciaCardiaca;
    }

    public int getFrecuenciaRespiratoria() {
        return frecuenciaRespiratoria;
    }

    public void setFrecuenciaRespiratoria(int frecuenciaRespiratoria) {
        this.frecuenciaRespiratoria = frecuenciaRespiratoria;
    }

    public float getTemperatura() {
        return temperatura;
    }

    public void setTemperatura(float temperatura) {
        this.temperatura = temperatura;
    }

    public int getIdPaciente() {
        return idPaciente;
    }

    public void setIdPaciente(int idPaciente) {
        this.idPaciente = idPaciente;
    }

    
} // class IndicadoresDTO
