package servidorAlertas.dto;

/**
* servidorAlertas/dto/PacienteDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public final class PacienteDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorAlertas.dto.PacienteDTO value = null;

  public PacienteDTOHolder ()
  {
  }

  public PacienteDTOHolder (servidorAlertas.dto.PacienteDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorAlertas.dto.PacienteDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorAlertas.dto.PacienteDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorAlertas.dto.PacienteDTOHelper.type ();
  }

}
