package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/NotificacionesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public abstract class NotificacionesPOA extends org.omg.PortableServer.Servant
 implements servidorNotificaciones.sop_corba.NotificacionesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("enviarAlerta", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // servidorNotificaciones/sop_corba/Notificaciones/enviarAlerta
       {
         servidorAlertas.dto.HistorialAlertasDTO objHistorial = servidorAlertas.dto.HistorialAlertasDTOHelper.read (in);
         this.enviarAlerta (objHistorial);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servidorNotificaciones/sop_corba/Notificaciones:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Notificaciones _this() 
  {
    return NotificacionesHelper.narrow(
    super._this_object());
  }

  public Notificaciones _this(org.omg.CORBA.ORB orb) 
  {
    return NotificacionesHelper.narrow(
    super._this_object(orb));
  }


} // class NotificacionesPOA
