package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public interface GestionPacientesOperations 
{
  boolean registrarPaciente (servidorAlertas.dto.PacienteDTO objPaciente, cliente.sop_corba.Paciente refCliente, org.omg.CORBA.StringHolder resultado);
  boolean actualizarPaciente (servidorAlertas.dto.PacienteDTO objPaciente);
  servidorAlertas.dto.PacienteDTO buscarPaciente (int idPaciente);
  boolean enviarIndicadores (int idPaciente, servidorAlertas.dto.IndicadoresDTO objIndicadores);
  boolean establecerMaxPacientes (int num);
  int getMaxPacientes ();
  int getNumRegistros ();
} // interface GestionPacientesOperations
