package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionPacientesPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public class GestionPacientesPOATie extends GestionPacientesPOA
{

  // Constructors

  public GestionPacientesPOATie ( servidorAlertas.sop_corba.GestionPacientesOperations delegate ) {
      this._impl = delegate;
  }
  public GestionPacientesPOATie ( servidorAlertas.sop_corba.GestionPacientesOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public servidorAlertas.sop_corba.GestionPacientesOperations _delegate() {
      return this._impl;
  }
  public void _delegate (servidorAlertas.sop_corba.GestionPacientesOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean registrarPaciente (servidorAlertas.dto.PacienteDTO objPaciente, cliente.sop_corba.Paciente refCliente, org.omg.CORBA.StringHolder resultado)
  {
    return _impl.registrarPaciente(objPaciente, refCliente, resultado);
  } // registrarPaciente

  public boolean actualizarPaciente (servidorAlertas.dto.PacienteDTO objPaciente)
  {
    return _impl.actualizarPaciente(objPaciente);
  } // actualizarPaciente

  public servidorAlertas.dto.PacienteDTO buscarPaciente (int idPaciente)
  {
    return _impl.buscarPaciente(idPaciente);
  } // buscarPaciente

  public boolean enviarIndicadores (int idPaciente, servidorAlertas.dto.IndicadoresDTO objIndicadores)
  {
    return _impl.enviarIndicadores(idPaciente, objIndicadores);
  } // enviarIndicadores

  public boolean establecerMaxPacientes (int num)
  {
    return _impl.establecerMaxPacientes(num);
  } // establecerMaxPacientes

  public int getMaxPacientes ()
  {
    return _impl.getMaxPacientes();
  } // getMaxPacientes

  public int getNumRegistros ()
  {
    return _impl.getNumRegistros();
  } // getNumRegistros

  private servidorAlertas.sop_corba.GestionPacientesOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionPacientesPOATie
