package clienteHabitacion.sop_corba;

/**
* cliente/sop_corba/PacienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public final class PacienteHolder implements org.omg.CORBA.portable.Streamable
{
  public clienteHabitacion.sop_corba.Paciente value = null;

  public PacienteHolder ()
  {
  }

  public PacienteHolder (clienteHabitacion.sop_corba.Paciente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = clienteHabitacion.sop_corba.PacienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        clienteHabitacion.sop_corba.PacienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return clienteHabitacion.sop_corba.PacienteHelper.type ();
  }

}
