package clienteHabitacion.sop_corba;


/**
* cliente/sop_corba/PacientePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public class PacientePOATie extends PacientePOA
{

  // Constructors

  public PacientePOATie ( clienteHabitacion.sop_corba.PacienteOperations delegate ) {
      this._impl = delegate;
  }
  public PacientePOATie ( clienteHabitacion.sop_corba.PacienteOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public clienteHabitacion.sop_corba.PacienteOperations _delegate() {
      return this._impl;
  }
  public void _delegate (clienteHabitacion.sop_corba.PacienteOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void alertarPaciente (String mensaje)
  {
    _impl.alertarPaciente(mensaje);
  } // alertarPaciente

  private clienteHabitacion.sop_corba.PacienteOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class PacientePOATie
