package clienteHabitacion.sop_corba;


/**
* cliente/sop_corba/PacienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gesPacientes.idl
* domingo 21 de junio de 2020 06:38:06 PM COT
*/

public interface PacienteOperations 
{
  void alertarPaciente (String mensaje);
  //String retornarmsj();
} // interface PacienteOperations
